# set -g default-terminal "st-256color"
set -g default-terminal "tmux-256color"
set -g mouse on
set -g destroy-unattached on
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf
bind-key u capture-pane \; save-buffer /tmp/tmux-buffer \; new-window -n "urlview" '$SHELL -c "urlview < /tmp/tmux-buffer"'

# DESIGN TWEAKS
set -g status-bg "#242424"
set -g status-fg "#fffbf6"
set -g status-right "#[bg=#3B3B3B] %Y-%m-%d #[bg=#525252] %H:%M "
