#!/usr/bin/env bash

switchRelay() {
    menucmd="dmenu -i"

    choice=$(printf "connect\ndisconnect" | dmenu -i -p "MullvadVPN")
    if command -v mullvad >/dev/null 2>&1; then
        mullvadVPN "$choice"
    elif command -v wg-quick >/dev/null 2>&1; then
        wireguardVPN "$choice"
    fi
}

mullvadVPN() {
    fullinfo="$(mullvad relay list)"
    countries="$(echo "$fullinfo" | grep -Eo "^[A-Za-z ]+ \([a-z]+\)")"

    case $1 in
        connect)
            CountryChoice="$(echo "$countries" | $menucmd -p "Select Country: ")"
            countrykey="$(echo "$CountryChoice" | grep -Eo "\([a-z]+\)" | tr -d '()')"

            # Extract cities by matching country code
            cities="$(awk -v code="$countrykey" '
                $0 ~ "\\(" code "\\)" {flag=1; next}
                /^[A-Za-z ]+ \([a-z]+\)/ && flag {flag=0}
                flag
            ' <<< "$fullinfo" | grep -Eo "^[[:space:]]*[A-Za-zäöü ,]+ \([a-z]+\)" | sed 's/^[ \t]*//')"

            cityChoice="$(echo "$cities" | $menucmd -p "Select City: ")"
            citykey="$(echo "$cityChoice" | grep -Eo "\([a-z]+\)" | tr -d '()')"

            servers="$(awk -v city="$citykey" '
                $0 ~ "\\(" city "\\)" {flag=1; next}
                /^[A-Za-z ]+ \([a-z]+\)/ && flag {flag=0}
                flag
            ' <<< "$fullinfo" | grep -Eo "[a-z-]+-[a-z]+-[0-9]{3}" )"

            if [ -n "$servers" ]; then
                serverChoice="$(echo "$servers" | $menucmd -p "Select Server: ")"
                echo "Selected server: $serverChoice"
                mullvad relay set location "$countrykey" "$citykey" "$serverChoice"
            else
                mullvad relay set location "$countrykey" "$citykey"
            fi

            mullvad connect;;
        disconnect)
            mullvad disconnect;;
    esac
}

case "$BLOCK_BUTTON" in
    1) ;; # switchRelay ;;
    3) ;;
    2) "$TERMINAL" -e "$EDITOR" "$0" ;; # Middle button
esac

if [[ "$(curl https://am.i.mullvad.net/connected)" == \
   *"You are connected to Mullvad"* ]]; then
    ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'
else
    echo "no VPN"
fi
