#!/usr/bin/env bash

case "$(printf "kill\nzzz\nreboot\nshutdown" | dmenu -i)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	zzz) loginctl suspend ;;
	reboot) loginctl reboot ;;
	shutdown) loginctl poweroff ;;
	*) exit 1 ;;
esac
