#!/bin/bash

APP_NAME="volume"
STEP=5

get_icon () {
  if [ $1 -lt 1 ]; then
    echo "muted"
  elif [ $1 -lt 20 ]; then
    echo "low"
  elif [ $1 -lt 70 ]; then
    echo "medium"
  else
    echo "high"
  fi
}

case "$1" in
  up)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ ${STEP}%+
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ \
               | awk '{print int($2*100)}')
    icon="audio-volume-$(get_icon $volume)-symbolic"
    ;;
  down)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ ${STEP}%-
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ \
               | awk '{print int($2*100)}')
    icon="audio-volume-$(get_icon $volume)-symbolic"
    ;;
  mute)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $3}')
    if [[ ! -z $muted ]]; then
      icon="audio-volume-muted-symbolic"
      volume=0
    else
      volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ \
                | awk '{print int($2*100)}')
    icon="audio-volume-$(get_icon $volume)-symbolic"
    fi
    ;;
  mute-mic)
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    muted_mic=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ \
                  | awk '{print $3}')
    if [[ ! -z $muted_mic ]]; then
      icon="microphone-sensitivity-muted-symbolic"
      volume=0
    else
      volume=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ \
                | awk '{print int($2*100)}')
      icon="microphone-sensitivity-$(get_icon $volume)-symbolic"
    fi
    ;;
  *)
    echo "Usage: $0 [up|down|mute|mute-mic]"
    exit 1
    ;;
esac

notify-send -a "$APP_NAME" \
            -h string:x-canonical-private-synchronous:volume \
            -h int:value:"$volume" \
            -i "$icon" \
            ""
