#!/bin/sh

APP_NAME="brightness"
STEP=5

case "$1" in
    up)
        light -A "+${STEP}%"
        ;;
    down)
        light -U "${STEP}%-"
        ;;
    *)
        echo "Usage: $0 [up|down]"
        exit 1
        ;;
esac

max=100
curr=$(printf "%.0f" $(light))
brightness=$(( (100 * curr) / max))
icon=$(get_icon $brightness)

notify-send -a "$APP_NAME" \
            -h string:x-canonical-private-synchronous:brightness \
            -h int:value:"$brightness" \
            -i "brightness-display-symbolic" \
            ""
