#!/usr/bin/env sh

# TODO add openbsd support
case "$(printf "kill\nVPN\ndisplay\nzzz\nreboot\nshutdown" | dmenu -i)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
    VPN) ~/scripts/statusbar/mullvad-vpn ;;
    display) ~/scripts/dwm/dwm-display ;;
	zzz) if command -v systemctl > /dev/null 2>&1
         then 
             systemctl suspend 
         elif command -v loginctl > /dev/null 2>&1
         then
             loginctl suspend 
         else 
             zzz
         fi ;;
	reboot) if command -v systemctl > /dev/null 2>&1
            then
                systemctl reboot
            elif command -v loginctl > /dev/null 2>&1
            then
                loginctl reboot 
            else
                shutdown -r now
            fi ;;
	shutdown) if command -v systemctl > /dev/null 2>&1
              then 
                  systemctl poweroff 
              elif command -v loginctl > /dev/null 2>&1
              then
                  loginctl shutdown 
              else 
                  shutdown -p now
              fi ;;
	*) exit 1 ;;
esac
