#!/usr/bin/env bash

case "$(printf "kill\nzzz\nreboot\nshutdown" | mew -i -l 4)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | mew -i -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	zzz) loginctl suspend -i ;;
	reboot) loginctl reboot -i ;;
	shutdown) loginctl poweroff -i ;;
	*) exit 1 ;;
esac
